name: Daily DRAMeXchange Crawl

on:
  schedule:
    - cron: "30 7 * * *"  # UTC 07:30 = KST 16:30
  workflow_dispatch:      # 수동 실행 가능

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Python 설정
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ 의존성 설치
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ scraper 실행 (working-directory 사용으로 경로 문제 방지)
      - name: Run scraper
        run: python main.py

      # 5️⃣ 변경된 엑셀 파일 커밋 & 푸시
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dram_price/DRAMeXchange_Semi_price.xlsx
          git diff --cached --quiet || git commit -m "Auto update: $(date '+%Y-%m-%d %H:%M')"
          git push
